spring:
  profiles:
    active: dev

---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev

eureka:
  client:
   service-uri:
     defaultZone: http://eureka-dev.com:7001/eureka/

---
server:
  port: 8202

spring:
  profiles: prod
  application:
    name: microservicecloud-config-client-prod

eureka:
  client:
    service-uri:
      defaultZone: http://eureka-prod.com:7001/eureka/

---
server:
  port: 8203

spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test

eureka:
  client:
    service-uri:
      defaultZone: http://eureka-test.com:7001/eureka/